#!name=Apple WLOC 定位修改（个人固定版）
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) | 个人备份固定版 | 选点页面: https://wloc-pages.pages.dev/
#!author=Yu9191 Rewrite | Backup by Evaleyan
#!homepage=https://github.com/Evaleyan/Shadowrocket-Backup
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/(?:gs-loc(?:-cn)?\.apple\.com|gsp-ssl\.ls\.apple\.com|bluedot\.is\.autonavi\.com(?:\.gds\.alibabadns\.com)?)\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/Evaleyan/Shadowrocket-Backup/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&randomRadius=0&logLevel=info

WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/Evaleyan/Shadowrocket-Backup/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, gsp-ssl.ls.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com
